# Generated by Django 5.0 on 2025-10-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(
                blank=True, help_text="City of purchase", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(
                default="USA", help_text="Country of purchase", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="Geographic region of purchase",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="state",
            field=models.CharField(
                blank=True,
                help_text="State/province of purchase",
                max_length=100,
                null=True,
            ),
        ),
    ]
