# Generated by Django 5.0 on 2025-10-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_city_order_country_order_region_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude of purchase location', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude of purchase location', null=True),
        ),
    ]
