# Generated by Django 5.0 on 2025-10-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='region',
        ),
    ]
